package WWW::SwaggerClient::Object::Connection;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'Connection',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'id',
    	format => '',
    	read_only => '',
    		},
    'user_id' => {
    	datatype => 'int',
    	base_name => 'user_id',
    	description => 'ID of user that owns this correlation',
    	format => '',
    	read_only => '',
    		},
    'connector_id' => {
    	datatype => 'int',
    	base_name => 'connector_id',
    	description => 'The id for the connector data source for which the connection is connected',
    	format => '',
    	read_only => '',
    		},
    'connect_status' => {
    	datatype => 'string',
    	base_name => 'connect_status',
    	description => 'Indicates whether a connector is currently connected to a service for a user.',
    	format => '',
    	read_only => '',
    		},
    'connect_error' => {
    	datatype => 'string',
    	base_name => 'connect_error',
    	description => 'Error message if there is a problem with authorizing this connection.',
    	format => '',
    	read_only => '',
    		},
    'update_requested_at' => {
    	datatype => 'DateTime',
    	base_name => 'update_requested_at',
    	description => 'Time at which an update was requested by a user.',
    	format => '',
    	read_only => '',
    		},
    'update_status' => {
    	datatype => 'string',
    	base_name => 'update_status',
    	description => 'Indicates whether a connector is currently updated.',
    	format => '',
    	read_only => '',
    		},
    'update_error' => {
    	datatype => 'string',
    	base_name => 'update_error',
    	description => 'Indicates if there was an error during the update.',
    	format => '',
    	read_only => '',
    		},
    'last_successful_updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'last_successful_updated_at',
    	description => 'The time at which the connector was last successfully updated.',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'When the record was first created. Use ISO 8601 datetime format',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'updated_at',
    	description => 'When the record in the database was last updated. Use ISO 8601 datetime format',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'user_id' => 'int',
    'connector_id' => 'int',
    'connect_status' => 'string',
    'connect_error' => 'string',
    'update_requested_at' => 'DateTime',
    'update_status' => 'string',
    'update_error' => 'string',
    'last_successful_updated_at' => 'DateTime',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'user_id' => 'user_id',
    'connector_id' => 'connector_id',
    'connect_status' => 'connect_status',
    'connect_error' => 'connect_error',
    'update_requested_at' => 'update_requested_at',
    'update_status' => 'update_status',
    'update_error' => 'update_error',
    'last_successful_updated_at' => 'last_successful_updated_at',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
