package WWW::SwaggerClient::Object::Credential;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'connector_id' => 'int',
    'attr_key' => 'string',
    'attr_value' => 'string',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime'
};

my $attribute_map = {
    'connector_id' => 'connector_id',
    'attr_key' => 'attr_key',
    'attr_value' => 'attr_value',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #connector_id
        'connector_id' => $args{'connector_id'}, 
        #attr_key
        'attr_key' => $args{'attr_key'}, 
        #attr_value
        'attr_value' => $args{'attr_value'}, 
        #created_at
        'created_at' => $args{'created_at'}, 
        #updated_at
        'updated_at' => $args{'updated_at'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
