package WWW::SwaggerClient::Object::Measurement;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'Measurement',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'id',
    	format => '',
    	read_only => '',
    		},
    'user_id' => {
    	datatype => 'int',
    	base_name => 'user_id',
    	description => 'ID of user that owns this measurement',
    	format => '',
    	read_only => '',
    		},
    'client_id' => {
    	datatype => 'string',
    	base_name => 'client_id',
    	description => 'client_id',
    	format => '',
    	read_only => '',
    		},
    'connector_id' => {
    	datatype => 'int',
    	base_name => 'connector_id',
    	description => 'The id for the connector data source from which the measurement was obtained',
    	format => '',
    	read_only => '',
    		},
    'variable_id' => {
    	datatype => 'int',
    	base_name => 'variable_id',
    	description => 'ID of the variable for which we are creating the measurement records',
    	format => '',
    	read_only => '',
    		},
    'source_id' => {
    	datatype => 'int',
    	base_name => 'source_id',
    	description => 'Application or device used to record the measurement values',
    	format => '',
    	read_only => '',
    		},
    'start_time' => {
    	datatype => 'string',
    	base_name => 'start_time',
    	description => 'Start Time for the measurement event. Use ISO 8601',
    	format => '',
    	read_only => '',
    		},
    'value' => {
    	datatype => 'double',
    	base_name => 'value',
    	description => 'The value of the measurement after conversion to the default unit for that variable',
    	format => '',
    	read_only => '',
    		},
    'unit_id' => {
    	datatype => 'int',
    	base_name => 'unit_id',
    	description => 'The default unit for the variable',
    	format => '',
    	read_only => '',
    		},
    'original_value' => {
    	datatype => 'double',
    	base_name => 'original_value',
    	description => 'Value of measurement as originally posted (before conversion to default unit)',
    	format => '',
    	read_only => '',
    		},
    'original_unit_id' => {
    	datatype => 'int',
    	base_name => 'original_unit_id',
    	description => 'Unit ID of measurement as originally submitted',
    	format => '',
    	read_only => '',
    		},
    'duration' => {
    	datatype => 'int',
    	base_name => 'duration',
    	description => 'Duration of the event being measurement in seconds',
    	format => '',
    	read_only => '',
    		},
    'note' => {
    	datatype => 'string',
    	base_name => 'note',
    	description => 'An optional note the user may include with their measurement',
    	format => '',
    	read_only => '',
    		},
    'latitude' => {
    	datatype => 'double',
    	base_name => 'latitude',
    	description => 'Latitude at which the measurement was taken',
    	format => '',
    	read_only => '',
    		},
    'longitude' => {
    	datatype => 'double',
    	base_name => 'longitude',
    	description => 'Longitude at which the measurement was taken',
    	format => '',
    	read_only => '',
    		},
    'location' => {
    	datatype => 'string',
    	base_name => 'location',
    	description => 'location',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'When the record was first created. Use ISO 8601 datetime format',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'updated_at',
    	description => 'When the record in the database was last updated. Use ISO 8601 datetime format',
    	format => '',
    	read_only => '',
    		},
    'error' => {
    	datatype => 'string',
    	base_name => 'error',
    	description => 'error',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'user_id' => 'int',
    'client_id' => 'string',
    'connector_id' => 'int',
    'variable_id' => 'int',
    'source_id' => 'int',
    'start_time' => 'string',
    'value' => 'double',
    'unit_id' => 'int',
    'original_value' => 'double',
    'original_unit_id' => 'int',
    'duration' => 'int',
    'note' => 'string',
    'latitude' => 'double',
    'longitude' => 'double',
    'location' => 'string',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime',
    'error' => 'string'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'user_id' => 'user_id',
    'client_id' => 'client_id',
    'connector_id' => 'connector_id',
    'variable_id' => 'variable_id',
    'source_id' => 'source_id',
    'start_time' => 'start_time',
    'value' => 'value',
    'unit_id' => 'unit_id',
    'original_value' => 'original_value',
    'original_unit_id' => 'original_unit_id',
    'duration' => 'duration',
    'note' => 'note',
    'latitude' => 'latitude',
    'longitude' => 'longitude',
    'location' => 'location',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
    'error' => 'error'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
