package WWW::SwaggerClient::Object::MeasurementRange;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'lower_limit' => 'int',
    'upper_limit' => 'int'
};

my $attribute_map = {
    'lower_limit' => 'lowerLimit',
    'upper_limit' => 'upperLimit'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #The timestamp of the earliest measurement for a user.
        'lower_limit' => $args{'lowerLimit'}, 
        #The timestamp of the most recent measurement for a user.
        'upper_limit' => $args{'upperLimit'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
