package WWW::SwaggerClient::Object::MeasurementExport;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'id' => 'int',
    'user_id' => 'int',
    'status' => 'string',
    'error_message' => 'string',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime'
};

my $attribute_map = {
    'id' => 'id',
    'user_id' => 'user_id',
    'status' => 'status',
    'error_message' => 'error_message',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #id
        'id' => $args{'id'}, 
        #ID of User
        'user_id' => $args{'user_id'}, 
        #Status of Measurement Export
        'status' => $args{'status'}, 
        #Error message
        'error_message' => $args{'error_message'}, 
        #created_at
        'created_at' => $args{'created_at'}, 
        #updated_at
        'updated_at' => $args{'updated_at'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
