package WWW::SwaggerClient::Object::UnitConversion;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'unit_id' => 'int',
    'step_number' => 'boolean',
    'operation' => 'boolean',
    'value' => 'double',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime'
};

my $attribute_map = {
    'unit_id' => 'unit_id',
    'step_number' => 'step_number',
    'operation' => 'operation',
    'value' => 'value',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #unit_id
        'unit_id' => $args{'unit_id'}, 
        #step in the conversion process
        'step_number' => $args{'step_number'}, 
        #0 is add and 1 is multiply
        'operation' => $args{'operation'}, 
        #number used in the operation
        'value' => $args{'value'}, 
        #created_at
        'created_at' => $args{'created_at'}, 
        #updated_at
        'updated_at' => $args{'updated_at'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
