package WWW::SwaggerClient::Object::VariableNew;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'name' => 'string',
    'category' => 'string',
    'unit' => 'string',
    'combination_operation' => 'string',
    'parent' => 'string'
};

my $attribute_map = {
    'name' => 'name',
    'category' => 'category',
    'unit' => 'unit',
    'combination_operation' => 'combinationOperation',
    'parent' => 'parent'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #User-defined variable display name.
        'name' => $args{'name'}, 
        #Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc.
        'category' => $args{'category'}, 
        #Abbreviated name of the default unit for the variable
        'unit' => $args{'unit'}, 
        #How to aggregate measurements over time.
        'combination_operation' => $args{'combinationOperation'}, 
        #Parent
        'parent' => $args{'parent'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
