package WWW::SwaggerClient::Object::VariableCategory;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'VariableCategory',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'id',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'Name of the category',
    	format => '',
    	read_only => '',
    		},
    'filling_value' => {
    	datatype => 'double',
    	base_name => 'filling_value',
    	description => 'Value for replacing null measurements',
    	format => '',
    	read_only => '',
    		},
    'maximum_allowed_value' => {
    	datatype => 'double',
    	base_name => 'maximum_allowed_value',
    	description => 'Maximum recorded value of this category',
    	format => '',
    	read_only => '',
    		},
    'minimum_allowed_value' => {
    	datatype => 'double',
    	base_name => 'minimum_allowed_value',
    	description => 'Minimum recorded value of this category',
    	format => '',
    	read_only => '',
    		},
    'duration_of_action' => {
    	datatype => 'int',
    	base_name => 'duration_of_action',
    	description => 'How long the effect of a measurement in this variable lasts',
    	format => '',
    	read_only => '',
    		},
    'onset_delay' => {
    	datatype => 'int',
    	base_name => 'onset_delay',
    	description => 'How long it takes for a measurement in this variable to take effect',
    	format => '',
    	read_only => '',
    		},
    'combination_operation' => {
    	datatype => 'string',
    	base_name => 'combination_operation',
    	description => 'How to combine values of this variable (for instance, to see a summary of the values over a month) 0 for sum OR 1 for mean',
    	format => '',
    	read_only => '',
    		},
    'updated' => {
    	datatype => 'int',
    	base_name => 'updated',
    	description => 'updated',
    	format => '',
    	read_only => '',
    		},
    'cause_only' => {
    	datatype => 'boolean',
    	base_name => 'cause_only',
    	description => 'A value of 1 indicates that this category is generally a cause in a causal relationship.  An example of a causeOnly category would be a category such as Work which would generally not be influenced by the behaviour of the user',
    	format => '',
    	read_only => '',
    		},
    'public' => {
    	datatype => 'int',
    	base_name => 'public',
    	description => 'Is category public',
    	format => '',
    	read_only => '',
    		},
    'outcome' => {
    	datatype => 'boolean',
    	base_name => 'outcome',
    	description => 'outcome',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'DateTime',
    	base_name => 'created_at',
    	description => 'When the record was first created. Use ISO 8601 datetime format',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'DateTime',
    	base_name => 'updated_at',
    	description => 'When the record in the database was last updated. Use ISO 8601 datetime format',
    	format => '',
    	read_only => '',
    		},
    'image_url' => {
    	datatype => 'string',
    	base_name => 'image_url',
    	description => 'Image URL',
    	format => '',
    	read_only => '',
    		},
    'default_unit_id' => {
    	datatype => 'int',
    	base_name => 'default_unit_id',
    	description => 'ID of the default unit for the category',
    	format => '',
    	read_only => '',
    		},
    
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'name' => 'string',
    'filling_value' => 'double',
    'maximum_allowed_value' => 'double',
    'minimum_allowed_value' => 'double',
    'duration_of_action' => 'int',
    'onset_delay' => 'int',
    'combination_operation' => 'string',
    'updated' => 'int',
    'cause_only' => 'boolean',
    'public' => 'int',
    'outcome' => 'boolean',
    'created_at' => 'DateTime',
    'updated_at' => 'DateTime',
    'image_url' => 'string',
    'default_unit_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'name' => 'name',
    'filling_value' => 'filling_value',
    'maximum_allowed_value' => 'maximum_allowed_value',
    'minimum_allowed_value' => 'minimum_allowed_value',
    'duration_of_action' => 'duration_of_action',
    'onset_delay' => 'onset_delay',
    'combination_operation' => 'combination_operation',
    'updated' => 'updated',
    'cause_only' => 'cause_only',
    'public' => 'public',
    'outcome' => 'outcome',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
    'image_url' => 'image_url',
    'default_unit_id' => 'default_unit_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
